# ==========================================
# RWS Study Configuration
# ==========================================

study:
  project_name: "RaveSim"
  environment: "Test"
  name: "RaveSim QA Validation Study"
  description: "Automated testing and validation study for RWS integration"
  metadata_version_oid: "1"
  seed: 12345
  speed_factor: 1.0
  interval_ms: 1500
  batch_percentage: 25

rws:
  version: "1.18.0"
  auth:
    users:
      - username: "testuser"
        password: "testpass"
      - username: "admin"
        password: "admin123"

logging:
  simulator: true
  api: true

structure:
  sites: 2
  subjects_per_site: 3

visits:
  - name: Screening
    day: 1
    forms: ["Demographics", "Vitals"]
    probability: 1.0
    simulate_delayed: true
    max_delay_days: 5
    simulate_missed: true
    missed_probability: 0.1
    partial_forms: true
    partial_field_probability: 0.2

  - name: Baseline
    day: 7
    forms: ["Labs", "ECG"]
    probability: 0.8
    simulate_delayed: true
    max_delay_days: 3
    simulate_missed: true
    missed_probability: 0.15

  - name: Follow-up
    day: 30
    forms: ["Vitals", "Adverse Events"]
    probability: 0.7
    simulate_missed: true
    missed_probability: 0.25
    partial_forms: true
    partial_field_probability: 0.1

queries:
  enabled: true
  missing_data_probability: 0.15
  out_of_range_probability: 0.05
  inconsistent_data_probability: 0.03
