study:
  id: "study-01"
  name: "Hypertension Simulation"
  seed: 42
  speed_factor: 60
  interval_ms: 5000
  batch_percentage: 10

structure:
  sites: 2
  subjects_per_site: 5

visits:
  - name: "Screening"
    day: 0
    forms: ["Demographics", "Vitals"]
    probability: 1.0
    simulate_missed: false
    simulate_delayed: false
    partial_forms: false
  - name: "Baseline"
    day: 14
    forms: ["Vitals", "Labs"]
    probability: 0.9
    simulate_missed: true
    simulate_delayed: true
    max_delay_days: 7
    partial_forms: true
    missing_field_probability: 0.2

queries:
  enabled: true
  missing_data_probability: 0.05
  out_of_range_probability: 0.02
