meta:
  id: rave-config
  title: Study Configuration Specification (V3 - TDD)
  version: 3.0.0
  description: |
    YAML configuration schema with behavioral semantics and invariants to support TDD and determinism.

structure:
  root:
    study:
      id: string
      name: string
      seed: number?
        behavior: "When provided, all random operations must be deterministic for reproducible tests."
      speed_factor: number
        behavior: "Multiplies simulated time progression relative to real time."
      interval_ms: number
        behavior: "Simulation tick interval (ms)."
      batch_percentage: number
        behavior: "Percentage of subjects updated per tick (0..100)."
    structure:
      sites: integer
        behavior: "Number of sites."
      subjects_per_site: integer
        behavior: "Subjects per site."
    visits:
      type: array
      items:
        ref: Visit
    queries:
      ref: QueryConfig

  Visit:
    description: Visit-level configuration.
    fields:
      name: string
      day: integer
        behavior: "Planned day offset from enrollment."
      forms: string[]
        behavior: "Forms captured at this visit."
      probability: number
        behavior: "Probability in [0..1] that the visit occurs when simulate_missed is true."
      simulate_missed: boolean
        behavior: "If true, visit may be skipped according to probability."
      simulate_delayed: boolean
        behavior: "If true, visit day may be shifted by 0..max_delay_days."
      max_delay_days: integer?
        behavior: "Required if simulate_delayed is true; must be >= 0."
      partial_forms: boolean
        behavior: "If true, fields may be nulled at random."
      missing_field_probability: number?
        behavior: "Probability in [0..1] for each field to be null when partial_forms is true."

  QueryConfig:
    description: Rules for automatic query generation.
    fields:
      enabled: boolean
      missing_data_probability: number
        behavior: "Probability in [0..1] of generating a MissingData query after form creation."
      out_of_range_probability: number
        behavior: "Probability in [0..1] of generating an OutOfRange query after form creation."

invariants:
  - name: BatchPercentBounds
    description: batch_percentage must be within 0..100
    rule: "0 <= study.batch_percentage <= 100"
  - name: VisitProbabilityBounds
    description: probability must be within 0..1
    rule: "for v in visits: 0 <= v.probability <= 1"
  - name: DelayRequiresMax
    description: simulate_delayed requires max_delay_days
    rule: "for v in visits: if v.simulate_delayed == true then v.max_delay_days is number and v.max_delay_days >= 0"
  - name: MissingFieldProbBounds
    description: missing_field_probability must be within 0..1 when present
    rule: "for v in visits: if v.missing_field_probability != null then 0 <= v.missing_field_probability <= 1"

examples:
  valid:
    - name: "Minimal deterministic study"
      yaml: |
        study:
          id: "s-001"
          name: "Deterministic Demo"
          seed: 42
          speed_factor: 60
          interval_ms: 5000
          batch_percentage: 10
        structure:
          sites: 2
          subjects_per_site: 5
        visits:
          - name: "Screening"
            day: 0
            forms: ["Demographics", "Vitals"]
            probability: 1.0
            simulate_missed: false
            simulate_delayed: false
            partial_forms: false
        queries:
          enabled: true
          missing_data_probability: 0.05
          out_of_range_probability: 0.02
  invalid:
    - name: "Delayed without max"
      yaml: |
        study:
          id: "bad"
          name: "NoMaxDelay"
          speed_factor: 10
          interval_ms: 1000
          batch_percentage: 5
        structure:
          sites: 1
          subjects_per_site: 1
        visits:
          - name: "Baseline"
            day: 14
            forms: ["Vitals"]
            probability: 0.9
            simulate_missed: true
            simulate_delayed: true
            partial_forms: false
        queries:
          enabled: false
